site_name: 'Helios server documentation'
nav:
  - Home: 'index.md'
  - Installation: 
    - Environment essentials : 'inst_env.md'
    - Setup authentication : 'inst_auth.md'
    - Prepare Django : 'inst_django.md'
    - Local development : 'inst_dev.md'
  - Deployment :
    - Heroku: 'deploy_heroku.md'
  - Concepts:
    - 'Verifiability' : 'con_e2ev.md'
    - 'Coercion' : 'con_coercion.md'
    - 'Helios' : 'con_helios.md'
  - Use cases:
    - 'Admin creates an election' : 'use_create_election.md'   
    - 'Admin tallies ballots' : 'use_admin_tallies_ballots.md'
    - 'Voter registers' : 'use_register_voter.md'
    - 'Voter votes' : 'use_voter_votes.md'
  - Reference:
    - 'Terms' : 'ref_terms.md'
    - 'Components' : 'ref_components.md'
    - 'Models' : 'ref_models.md'
    - 'Academic papers' : 'ref_literature.md'
  - 'FAQs' : 'faq_faq1.md'
  - 'Acknowledgements' : 'acknowledgements.md'

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - footnotes

###
### Quick reference
###

##
## Receipes 
##

# Virtual env
# source venv/bin/activate

# Local server
# mkdocs serve -a 127.0.01:8001

# Build docs into site folder
# mkdocs build

# Upgrade material theme
# pip install --upgrade mkdocs-material

# Material extensions: https://squidfunk.github.io/mkdocs-material/extensions/admonition/

##
## FAQs 
##

# FAQs Model on [POLYAS](https://www.polyas.com/online-voting/support/faq)
# Explanations on http://www.easiestelection.com/index.html

##
## Google analytics - paste into <Head>
##

# <!-- Global site tag (gtag.js) - Google Analytics -->
# <script async src="https://www.googletagmanager.com/gtag/js?id=UA-150810154-1"></script>
# <script>
#   window.dataLayer = window.dataLayer || [];
#   function gtag(){dataLayer.push(arguments);}
#   gtag('js', new Date());

#   gtag('config', 'UA-150810154-1');
# </script>