site_name: 'Helios server documentation'
nav:
  - Home: 'index.md'
  - Installation: 
    - Environment essentials : 'inst_env.md'
    - Setup authentication : 'inst_auth.md'
    - Prepare Django : 'inst_django.md'
    - Local development : 'inst_dev.md'
    - Deployment : 'inst_deploy.md'
  - Concepts:
    - 'Voting' : 'con_voting.md'
  - Use cases:
    - 'Admin creates an election' : 'use_create_election.md'
    - 'Admin retrieves ballots' : 'use_admin_retrieves_ballots.md'
    - 'Admin tallies ballots' : 'use_admin_tallies_ballots.md'
    - 'Admin announces results' : 'use_admin_announces_results.md'
    - 'Voter registers' : 'use_register_voter.md'
    - 'Voter votes' : 'use_voter_votes.md'
    - 'Voter saves ballot' : 'use_voter_saves_ballot.md'
    - 'Verifier verifies all counted' : 'use_verifier_ballots.md'
    - 'Verifier verifies correctness' : 'use_verifier_count_correct.md'
    - 'All uses cases on a page' : 'use_usecases.md'
  - Reference:
    - 'Terms' : 'ref_terms.md'
    - 'Components' : 'ref_components.md'
    - 'Models' : 'ref_models.md'
    - 'Academic papers' : 'ref_literature.md'
  - 'FAQs' : 'faq_faq1.md'
  - 'Acknowledgements' : 'acknowledgements.md'
  - 'TODO' : 'todo.md'
theme:
  name: 'material'

markdown_extensions:
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde


# Quick reference

# Local server
# mkdocs serve -a 127.0.01:8001

# Build docs into site folder
# mkdocs build

# Material extensions: https://squidfunk.github.io/mkdocs-material/extensions/admonition/

# FAQs Model on [POLYAS](https://www.polyas.com/online-voting/support/faq)